# import gzip for gzip file handling
import gzip 
import json
from pathlib import Path
# import os for operating system related functions
import os

# import psycopg2 for database connection
import psycopg2
# import execute_values for bulk insert
from psycopg2.extras import execute_values
# import dotenv for environment variables
from dotenv import load_dotenv




load_dotenv()# load the environment variables from the .env file
RAW_FILE=Path("data/raw/2026-08-01-16.json.gz")
BATCH_SIZE=1000


CREATE_TABLE="""
CREATE TABLE IF NOT EXISTS raw_data
( event_id TEXT PRIMARY KEY,
event_type TEXT,
created_at TIMESTAMPTZ,
payload JSONB NOT NULL
);
"""
# insert data into the raw_data table after rows are generated by the rows_from_file function
INSERT_DATA="""
INSERT INTO raw_data(event_id, event_type, created_at, payload)
VALUES %s
ON CONFLICT (event_id) DO NOTHING;
"""
def rows_from_file(path: Path):
    with gzip.open(path, "rt", encoding="utf-8") as f:
        for i in f:
            event= json.loads(i)
            yield(
                event["id"],
                event["type"],
                event["created_at"],
                json.dumps(event)
            )

def load_data(path: Path) -> None:
    conn=psycopg2.connect(os.environ["DATABASE_URL"])
    try:
        with conn.cursor() as csr:
            csr.execute(CREATE_TABLE)
            batch=[]
            total=0
            for i in rows_from_file(path):
                batch.append(i)
                if len(batch)>=BATCH_SIZE:
                    execute_values(csr, INSERT_DATA, batch)
                    total+=len(batch)
                    batch=[]
            if batch:
                execute_values(csr, INSERT_DATA, batch)
                total+=len(batch)
            conn.commit()
    finally:
        conn.close()
if __name__=="__main__":
    load_data(RAW_FILE)        


